sharehouse-sanhaimu/oshi-ramen

- api/app/controllers/V1/ramen_controller.rb
- view/src/app/page.tsx
- view/src/components/Ramen.tsx
- view/src/components/RamenGallery.tsx
- view/src/components/RamenModal.tsx
- view/src/types/RamenGallery/index.tsx
> 画像を送受信する画面の完成

- api/app/controllers/V1/users_controller.rb
- api/config/routes.rb
close #issue番号
```
curl -X GET "http://localhost:8000/v1/users/1" \        
-H "Content-Type: application/json"
```
response
```
{"message":"User found successfully","data":{"id":1,"google_id":"test1","nickname":"テストユーザー","created_at":"2025-03-01T18:25:09.944Z","updated_at":"2025-03-01T18:25:09.944Z","icon_url":""}
```
> 特定のUser情報を取得する機能を実装

- api/app/controllers/s3_controller.rb
- api/config/routes.rb
- api/test/controllers/s3_controller_test.rb
close #issue番号
- S3にImageを保存するエンドポイント
- 
body
```
{
file: string
}
```
> S3にImageを保存するエンドポイントを作成

- view/src/app/page.tsx
> Fix/nose/post UI

- api/app/controllers/V1/users_controller.rb
- api/app/services/get_image_from_url.rb
- api/app/services/upload_to_s3.rb
- api/db/migrate/20250301231833_add_icon_url_to_users.rb
- api/db/schema.rb
- view/src/lib/signInAndUp.ts
> iconを保存する機能を追加

- view/src/app/login/page.tsx
close #issue番号
- login画面のワードを変更
> ログイン画面のワードを変更

- api/config/environments/development.rb
- compose.prod.yml
- magazine/main.py
- view/src/app/layout.tsx
- view/src/app/page.tsx
- view/src/components/Header.tsx
- view/src/components/magazineModal.tsx
- view/src/lib/signInAndUp.ts
> デプロイ時のエラーを修正

- .github/workflows/release.yml
- .github/workflows/released.yml
- .vscode/settings.json
> イメージをpushするワークフローを追加

- .github/workflows/released.yml
> fix: 起動イベントを修正

- .github/workflows/released.yml
> fix:  指定のワークフローの終了をトリガーに修正

- .github/workflows/released.yml
> fix: 指定のレジストリに対してログイン

- .github/workflows/release.yml
- .github/workflows/released.yml
> fix: releaseイベントのバージョンの値を利用してdockerにタグ付け

- .github/workflows/released.yml
> fix: 最新のtag情報を取得するshellを追加

- .github/workflows/released.yml
> fix: contextを設定

- .github/workflows/released.yml
> fix: pathを修正

- .github/workflows/released.yml
> fix: tagにドメインを追加

- .github/workflows/released.yml
> buildのactionsを改良

- api/Gemfile
- api/Gemfile.lock
- api/bin/docker-entrypoint
- api/config/environments/production.rb
- api/prod.Dockerfile
> docker fileを修正

- .github/workflows/released.yml
> del: マルチプラットフォームbuildをやめる

- api/config/initializers/cors.rb
> fix: corsにhttpsを追加

- api/config/application.rb
> del: 不要なcors設定を削除

- api/app/services/upload_to_s3.rb
> feat: regionを表示

- .github/workflows/released.yml
> fix: ファイル名が見つからないためでバックコードを追加

- .github/workflows/released.yml
> fix: ディレクトリ移動を修正

- .github/workflows/released.yml
> fix: タグの指定を修正

- .github/workflows/released.yml
> fix: 不要なコードを削除

- .github/workflows/release.yml
> fix: 叩くURLを修正
